-- PostgreSQL/Neon schema and safe commands for course enrollment management.
-- Replace :course_id and :user_id with numeric IDs in your SQL client.

CREATE TABLE IF NOT EXISTS course_enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    enrolled_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL,
    expires_at TIMESTAMP NULL,
    progress_percent INTEGER NOT NULL DEFAULT 0
        CHECK (progress_percent BETWEEN 0 AND 100),
    score_percent INTEGER NULL
        CHECK (score_percent BETWEEN 0 AND 100),
    version BIGINT,
    CONSTRAINT uk_course_enrollment_course_user UNIQUE (course_id, user_id),
    CONSTRAINT fk_course_enrollment_course
        FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT fk_course_enrollment_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_course_enrollments_course_id
    ON course_enrollments(course_id);
CREATE INDEX IF NOT EXISTS idx_course_enrollments_user_id
    ON course_enrollments(user_id);

-- ENROLL one active learner. Returns the inserted row.
INSERT INTO course_enrollments (course_id, user_id)
SELECT :course_id, u.id
FROM users u
WHERE u.id = :user_id
  AND u.active = TRUE
  AND UPPER(REPLACE(TRIM(u.role), 'ROLE_', '')) = 'LEARNER'
  AND EXISTS (SELECT 1 FROM courses c WHERE c.id = :course_id)
ON CONFLICT (course_id, user_id) DO NOTHING
RETURNING *;

-- UNENROLL one learner. Returns the deleted row.
DELETE FROM course_enrollments
WHERE course_id = :course_id
  AND user_id = :user_id
RETURNING *;

